### ISSUE TITLE
hide_keywords does not work

### ISSUE THREAD

**Issue by sysopcorner** [packetbeat/packetbeat#92]
First of all I would like to thank you for superb project. I was watching it for a long time and now I'm using it in one of projects. It helps a lot while debugging performance issues, etc.

But we definitelly require hide certain parameters from
a) GET url
b) POST parameters
I tryied the following config in packetbeat agent versions 0.4.1 and 0.4.3
> [passwords]
> hide_keywords = ["number=", "password=", "passwd=", "Password="]

and used curl for sending requests:
> curl --header 'Host: our.external.lb.hostname'  "http://localhost:8080/test?app?pass=test" -u user: -d "Password=my_secret_pass" -d "Password=my_secret_password_2"

Non of versions works as I expected. 
In 0.4.1 version I see whole URL and POST parameters as follows:

>Content-Type: application/x-www-form-urlencoded
> Password=my_secret_pass&pass=********************

>Content-Type: application/x-www-form-urlencoded
> Password=my_secret_pass&Password=my_secret_password_2

As you notice first parameter is not hidden.

In 0.4.3 version I see whole URL and not POST parameters at all.
> Content-Type: application/x-www-form-urlencoded
> 

Can you give me a hand with this?

**Comment by tsg** [comment]
In 0.4.3, to get the full body you need this configuration:

    [http]
    send_headers = ["content-type"]
    include_body_for = ["application/x-www-form-urlencoded"]

The reason is that the content-type header is needed for the `include_body_for` option to work. But there are some issues with the censoring code which is unchanged between the versions, so when you do that you'll get similar results.

The censoring part is a pretty bad hack right now, I could fix it for this use case but I'm afraid it would leak information in other cases. So a better approach that we want to take is to do proper parameter parsing. I'll update this ticket when we have more information.

**Comment by sysopcorner** [comment]
Ok thanks for your response. We are waiting then.
